cache:
    paths:
        - vendor/

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - composer update --no-progress
        - bin/console --env=test doctrine:database:create
        - bin/console --env=test doctrine:schema:create
        - vendor/bin/phpunit -c ./
        - vendor/bin/phpcpd src/
        - vendor/bin/phpcs -n --extensions=php --standard=PSR2 src/
deploy:
    stage: deploy
    only:
        - master
    script:
        - rm -rf var/cache/* var/logs/*
        - cp app/config/parameters.yml.dist app/config/parameters.yml
        - bin/console --env=prod doctrine:database:create
        - bin/console --env=prod doctrine:schema:create
        - composer install -o --no-dev
        - ( find . -type d -name ".git") | xargs rm -rf
        - mkdir dist
        - zip -r dist/${CI_PROJECT_NAME}.zip ./

    artifacts:
        name: ${CI_PROJECT_NAME}
        paths:
            - "${CI_PROJECT_DIR}/dist/*.zip"
        expire_in: 1 day
