cache:
    paths:
        - vendor/

stages:
    - test
    - deploy

before_script:
    - composer update --no-progress
    - bin/console --env=test doctrine:database:create
    - bin/console --env=test doctrine:schema:create

test:
    stage: test
    script:
        - vendor/bin/phpunit -c ./
        - vendor/bin/phpcpd src/
        - vendor/bin/phpcs -n --extensions=php --standard=PSR2 src/

deploy:
    stage: deploy
    only:
        - master
    script:
        - ( find . -type d -name ".git") | xargs rm -rf
    artifacts:
        name: ${CI_PROJECT_NAME}
        paths:
            - ./
        expire_in: 1 day
