image: wg-runner/php7

cache:
    paths:
        - bin/
        - vendor/

before_script:
#  - phpdismod xdebug
  - composer update --no-progress
  - vendor/bin/console --env=test doctrine:database:create
  - vendor/bin/console --env=test doctrine:schema:create
#  - phpenmod xdebug

stages:
  - test
  - deploy

test_job:
    stage: test
    script:
        - vendor/bin/phpunit -c app/ --coverage-html /packages/report/metador2/coverage
        - vendor/bin/phpcpd src/
        - vendor/bin/phpcs -n --extensions=php --standard=PSR2 src/

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - app/Resources/scripts/build.sh
