image: wg-ubuntu-14-04-basic

cache:
    paths:
        - bin/
        - vendor/

before_script:
  - composer update --no-progress

stages:
  - test
  - build

job1:
    stage: test
    script:
        - bin/phpunit -c app/

job2:
    stage: build
    only:
        - master
    script:
        - echo "hello world"
