image: wg-ubuntu-14-04-basic

cache:
    paths:
        - bin/
        - vendor/

before_script:
  - composer update --no-progress

stages:
  - test
  - deploy

test_job:
    stage: test
    script:
        # Run unit tests
        - bin/phpunit -c app/
        # Check code for PSR2 convention
        - bin/phpcs -n --extensions=php --standard=PSR2 src/
        # Run the copy paste detector
        # - bin/phpcpd src/

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - chmod +x app/Resources/scripts/build.sh
        - app/Resources/scripts/build.sh
