image: wg-ubuntu-14-04-basic

cache:
    paths:
        - bin/
        - vendor/

before_script:
  - php5dismod xdebug
  - composer update --no-progress
  - php5enmod xdebug

stages:
  - test
  - deploy

test_job:
    stage: test
    script:
        - chmod +x app/Resources/scripts/test.sh
        - app/Resources/scripts/test.sh

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - chmod +x app/Resources/scripts/build.sh
        - app/Resources/scripts/build.sh
