version: '3'
services:
    postgis:
        build:
            context: ./docker/postgis
            args:
                var_uid: ${CURRENT_UID}
                var_gid: ${CURRENT_GID}
        environment:
            POSTGRES_USER: ${PGSQL_USER}
            POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
        volumes:
            - ./docker/postgis/data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    php-fpm:
        build:
            context: ./docker/php-fpm
            args:
                var_uid: ${CURRENT_UID}
                var_gid: ${CURRENT_GID}
                var_remove_host: ${IP_ADDRESS}
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - PGSQL_USER=${PGSQL_USER}
            - PGSQL_PASSWORD=${PGSQL_PASSWORD}
            - XDEBUG_REMOTE_HOST=${IP_ADDRESS}
            - WAIT_HOSTS=postgis:5432
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
        volumes:
            - ./:/var/www
        depends_on:
            - postgis
        command: sh -c "/bin/wait && php-fpm"
    nginx:
        build:
            context: ./docker/nginx
            args:
                var_uid: ${CURRENT_UID}
                var_gid: ${CURRENT_GID}
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8000:8000"
        depends_on:
            - php-fpm
