where_group_core:
    resource: "@MetadorCoreBundle/Controller/"
    type:     annotation

where_group_user:
    resource: "@MetadorUserBundle/Controller/"
    type:     annotation

where_group_plugin:
    resource: "@MetadorPluginBundle/Controller/"
    type:     annotation

_plugins:
    resource: "../../var/plugins/plugins_routing.yml"
