wheregroup_core:
    resource: "@MetadorCoreBundle/Controller/"
    type:     annotation

wheregroup_user:
    resource: "@MetadorUserBundle/Controller/"
    type:     annotation

wheregroup_plugin:
    resource: "@MetadorPluginBundle/Controller/"
    type:     annotation

metador_address:
    resource: "@MetadorAddressBundle/Controller/"
    type:     annotation
    prefix:   /

_plugins:
    resource: "../../var/config/plugins_routing.yml"
