where_group_core:
    resource: "@WhereGroupCoreBundle/Controller/"
    type:     annotation

where_group_user:
    resource: "@WhereGroupUserBundle/Controller/"
    type:     annotation

where_group_plugin:
    resource: "@WhereGroupPluginBundle/Controller/"
    type:     annotation

_plugins:
    resource: "../../var/plugins/plugins_routing.yml"
