metador-core:
    origin: WhereGroup
    type: system
    name: Hauptanwendung
    active: true
    settings:
        session_timeout_popup:
            frontend: true
            default: 60
            placeholder: 60
            type: string
            label: Session Timeout Meldung
            description: Beschreibungstext
