metador_core:
    origin: WhereGroup
    type: system
    name: Hauptanwendung
    active: true
    settings:
        session_timeout_popup:
            frontend: true
            default: 60
            placeholder: 60
            type: string
            label: Session Timeout Meldung
            description: Beschreibungstext
        system_message:
            type: text
            label: Systemmeldung
            description: Zum setzten von Systemmeldung, Text eingeben und speichern. Markdown wird unterstützt.
        proxy_host:
            type: string
            label: Proxy Host
        proxy_port:
            type: string
            label: Proxy Port
        proxy_user:
            type: string
            label: Proxy User
        proxy_pass:
            type: string
            label: Proxy Password
