# Controller
#DisallowSecurityAutorizationCheckerService:
#    message: "Dont use the authorization_checker service. Use $this->denyAccessUnlessGranted() instead."
#    regexp: "/\\$this\\->get\\('security.authorization_checker'\\)\\->isGranted\\(/"
DisallowMethodAnnotation:
    message: "Dont use @Method() Annotation, use @Route(methods={\"\"}) instead."
    regexp: "/@Method\\(/"
DisallowTemplateAnnotation:
    message: "Dont use @Template() Annotation, use $this->render(); instead."
    regexp: "/@Template\\(/"
DeprecatedMethodNamespace:
    message: "Namespace Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method is deprecated,
    use Symfony\\Component\\Routing\\Annotation\\Route instead."
    regexp: "/Sensio\\\\Bundle\\\\FrameworkExtraBundle\\\\Configuration\\\\Method/"
DeprecatedRouteNamespace:
    message: "Namespace Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route is deprecated,
    use Symfony\\Component\\Routing\\Annotation\\Route instead."
    regexp: "/Sensio\\\\Bundle\\\\FrameworkExtraBundle\\\\Configuration\\\\Route/"
DissallowDebug:
    message: "Remove Debug class"
    regexp: "/WhereGroup\\\\CoreBundle\\\\Component\\\\Utils\\\\Debug/"
# Other
DisallowDump:
    message: "Remove dump() or var_dump()."
    regexp: "/[^:>](dump|var_dump)\\(/"
# Javascript
DisallowConsoleLog:
    message: "Remove console.log()."
    regexp: "/console\\.log\\(/"
    extensions: ["js"]
#DisallowServiceXml:
#    message: "Dont use services.xml. Use services.yml instead."
#    regexp: "/services\\.xml/"
#DisallowInlineStyle:
#    message: "Dont use inline styling."
#    regexp: "/style[ ]?=[ ]?['|\\\"]+/"
#    extensions: ["twig"]
