services:
    WhereGroup\CoreBundle\Service\:
        resource: '%kernel.project_dir%/src/WhereGroup/CoreBundle/Service'
        public: true
        autowire: true
        autoconfigure: true
    WhereGroup\UserBundle\Component\UserInterface: '@metador_user'
    WhereGroup\PluginBundle\Component\Plugin: '@metador_plugin'
    WhereGroup\CoreBundle\Component\Logger: '@metador_logger'
    WhereGroup\CoreBundle\Component\Utils\Process: '@metador_process'
    WhereGroup\AddressBundle\Component\Address: '@metador_address'
    WhereGroup\CoreBundle\Component\Metadata\Validator: '@metador_metadata_validator'
    WhereGroup\CoreBundle\Component\Configuration: '@metador_configuration'
